name: Deploy to Plugin Staging
on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
jobs:
  tag:
    name: Deploy to plugin staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Build theme
        working-directory: ./vimeography-harvestone
        run: |
          npm ci
          npm run build
      - name: Build admin app
        working-directory: ./lib/admin/app
        run: |
          npm ci
          npm run build
      - name: Deploy build to staging WordPress server
        run: |
          # remove non-wordpress deployable files
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" trunk/ --delete --delete-excluded
          # rsync up to staging
          # https://explainshell.com/explain?cmd=rsync+-p+--chmod%3D%2Brwx+-e+%22ssh+-i+userserver.pem%22+--copy-unsafe-links+-rz+user%40server%3A~%2F+%2Fdb_backups%2Fwww%2F
          sshpass -p "${{ secrets.VIMEOGRAPHY_WP_STAGING_SSH_PASSWORD }}" rsync -azv --no-o --no-g --chmod=ugo=rwX --delete --exclude=logs "$GITHUB_WORKSPACE/trunk/" root@${{ secrets.VIMEOGRAPHY_WP_STAGING_SSH_HOST }}:/var/www/html/wp-content/plugins/vimeography
